FROM python:3.13-slim

# Install netcat for entrypoint wait script
RUN apt-get update && apt-get install -y netcat-openbsd && rm -rf /var/lib/apt/lists/*

# Create non-root user
RUN useradd -m shifat

WORKDIR /home/shifat/app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN chmod +x entrypoint.sh

# Switch to non-root
USER shifat

ENTRYPOINT ["./entrypoint.sh"]
