FROM python:3.13-slim
WORKDIR user/app
COPY . .
EXPOSE 8080
RUN pip install --no-cache-dir -r requirements.txt
RUN useradd shifat
USER shifat

CMD ["uvicorn","main:app","--host","0.0.0.0","--port","8080"]
